language: crystal

install:
  - shards install

script:
  # Spec
  - crystal spec spec/**/*
  # Format
  - crystal tool format --check
  # Lint
  - ./bin/ameba
  # Generate Documentation
  - crystal docs

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  project_name: crystal-client
  target_branch: docs
  on:
    branch: master
  local_dir: docs
